apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-service-2-read
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]